//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Link_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Left_Fee
    {
        public Left_Fee()
        {
            this.Payment_Details = new HashSet<Payment_Detail>();
        }
    
        public int Id { get; set; }
        public System.DateTime Month { get; set; }
        public long AdmissionFee { get; set; }
        public long ExaminationFee { get; set; }
        public long TutionFee { get; set; }
        public long RefreshmentAccFee { get; set; }
        public long LabFee { get; set; }
        public long ProjectFee { get; set; }
        public long AnnualCharges { get; set; }
        public long AdminCharges { get; set; }
        public long SmartClassCharges { get; set; }
        public long ComputerFeeYearly { get; set; }
        public long ComputerFeeMonthly { get; set; }
        public long DevelopmentChargesYearly { get; set; }
        public long TransportFee { get; set; }
        public long LateFee { get; set; }
        public long TotalFee { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Payment_Detail> Payment_Details { get; set; }
    }
}
