//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Link_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Detail
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string ModeOfPayment { get; set; }
        public long LeftFeesAmount { get; set; }
        public int LeftfeesId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsDeleted { get; set; }
        public bool isPaid { get; set; }
    
        public virtual Left_Fee Left_Fees { get; set; }
        public virtual Student Student { get; set; }
    }
}
